[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/resources/feminist-knowledge-translation/fillable-template.pdf"
  to =   "/resources/feminist-knowledge-translation-fillable-template.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
